# Generated by Django 6.0.5 on 2026-06-15 10:06

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('it', 'IT'), ('ecology', 'экология'), ('art', 'искусство'), ('education', 'образование'), ('sport', 'спорт'), ('social', 'социальная помощь'), ('business', 'бизнес и стартапы'), ('other', 'другое')], max_length=50, verbose_name='Категория')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('open', 'идет набор'), ('team_assembled', 'команда собрана'), ('in_progress', 'проект запущен'), ('completed', 'завершен'), ('archived', 'в архиве')], max_length=50, verbose_name='Статус')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Инициатива',
                'verbose_name_plural': 'Инициативы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Что нужно делать')),
                ('count_needed', models.PositiveIntegerField(default=1, verbose_name='Необходимое количество')),
                ('count_filled', models.PositiveIntegerField(default=0, verbose_name='Количество набранных')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыт для откликов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='ideas.idea', verbose_name='Инициатива')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='users.skill', verbose_name='требуемый навык')),
            ],
            options={
                'verbose_name': 'Роль в инициативе',
                'verbose_name_plural': 'Роли в инициативе',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('pending', 'на рассмотрении'), ('approved', 'принят'), ('rejected', 'отклонен')], default='pending', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ideas.idea', verbose_name='Инициатива')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Кто откликнулся')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ideas.idearole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['status', 'is_published'], name='ideas_idea_status_d3df40_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['category'], name='ideas_idea_categor_13cd60_idx'),
        ),
        migrations.AddConstraint(
            model_name='idearesponse',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_response_per_role'),
        ),
    ]
