# Generated by Django 6.0.5 on 2026-06-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idearole',
            name='skill',
        ),
        migrations.CreateModel(
            name='IdeaRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='Если False, навык будет считаться преимуществом, но не строгим требованием', verbose_name='Обязательный навык')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessary_skills', to='ideas.idearole', verbose_name='Роль')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessary_in_roles', to='users.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Требование к навыку в роли',
                'verbose_name_plural': 'Требования к навыкам в ролях',
            },
        ),
        migrations.AddField(
            model_name='idearole',
            name='skills',
            field=models.ManyToManyField(related_name='relose_necessary_this', through='ideas.IdeaRoleSkill', to='users.skill', verbose_name='Необходимые навыки'),
        ),
        migrations.AddConstraint(
            model_name='idearoleskill',
            constraint=models.UniqueConstraint(fields=('role', 'skill'), name='unique_role_skill_in_role'),
        ),
    ]
