# Generated by Django 6.0.5 on 2026-06-24 16:38

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_remove_idearole_skill_idearoleskill_idearole_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Описание'),
        ),
    ]
