# Generated by Django 6.0.5 on 2026-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_description'),
        ('users', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='about',
            field=models.CharField(max_length=250, null=True, verbose_name='Суть идеи'),
        ),
        migrations.AlterField(
            model_name='idearole',
            name='skills',
            field=models.ManyToManyField(related_name='roles_necessary_this', through='ideas.IdeaRoleSkill', to='users.skill', verbose_name='Необходимые навыки'),
        ),
    ]
