# Generated by Django 6.0.5 on 2026-07-04 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0004_idea_about_alter_idearole_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribers_count', models.PositiveIntegerField(default=0, editable=False)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='ideas.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['idea', 'user'], name='subscriptio_idea_id_ecea77_idx'), models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_dbd9bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idea'), name='unique_user_idea_subscription')],
            },
        ),
    ]
