# Generated by Django 6.0.5 on 2026-07-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers_count',
        ),
    ]
