# Generated by Django 6.0.5 on 2026-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('it_dev', 'IT и Разработка'), ('design', 'Дизайн и Графика'), ('marketing', 'Маркетинг, PR и SMM'), ('content', 'Тексты, Копирайтинг и Переводы'), ('media', 'Видео, Аудио и Фотография'), ('management', 'Управление проектами (PM)'), ('events', 'Организация мероприятий'), ('finance', 'Финансы и Фандрайзинг'), ('legal', 'Юридическая помощь'), ('education', 'Образование, Менторство и Психология'), ('research', 'Наука и Аналитика'), ('art', 'Искусство и Культура'), ('volunteering', 'Волонтёрство и логистика'), ('health', 'Здоровье и Медицина'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Категория'),
        ),
    ]
